dementia_news_research_task:
  description: >
    Research the latest dementia news and developments that would be relevant to both patients and professionals alike
    Focus on:
    - Treatment breakthroughs and new therapies
    - Lifestyle tips and prevention strategies  
    - Support resources and community programs
    - Patient success stories and hope-inspiring developments
  expected_output: >
    Two different lists, one with ten articles summarised and prepared for any consumer with very little knowledge to read. And another one which contains a detailed insight into the latest developments for medical professionals in dementia developments.
  agent: dementia_news_analyst


dementia_news_report_task:
  description: >
    Reformat the two lists of these articles, into json associative arrays
    Focus on:
    - Ensuring the articles do not lead to dead links 
    - Have consise but descriptive snippets 
  expected_output: >
    Two json files with ten values storing a headline,a snippet summary of the article that is relevant to professionals, and the url of said article 
  agent: dementia_news_reporter
